{% set data = load_setup_py_data() %}

package:
  name: gateway
  version: {{ GIT_DESCRIBE_TAG|replace('v', '') }}

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  string: np{{ NPY_VER|replace('.', '') }}py{{ PY_VER|replace('.', '') }}_{{ (
    GIT_BUILD_STR if GIT_DESCRIBE_NUMBER|int != 0 else '0'
  ) }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  git_url: ../../

requirements:
  build:
    - python {{ PY_VER }}*
    - libgfortran ==1  # [linux and (np == 19)]
    {% for req in data.get('build_requires', []) -%}
    - {{req}}
    {% endfor %}
  run:
    - python
    - libgfortran ==1 # [linux and (np == 19)]
    {% for req in data.get('install_requires', []) -%}
    - {{req}}
    {% endfor %}

test:
  # Python imports
  imports:
    - gateway

about:
  home: https://gateway.io
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
